services:
  pgdatabase:
    image: postgres
    container_name: pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: shekobeko62
      POSTGRES_DB: ny_taxi
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5051:5051"
    depends_on:
      - pgdatabase
    environment:
      DATABASE_URL: postgresql://root:shekobeko62@pgdatabase:5432/ny_taxi
  jupyter:
    image: jupyter/datascience-notebook
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"
